import os
import openai

# Set your OpenAI API key as an environment variable named "API_KEY"
openai.api_key = os.environ.get("API_KEY")


# Define a function to interact with the chatbot
def chatbot(prompt):
    # Create a conversation with the GPT-3.5 Turbo model
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt},
        ],
    )

    # Return the message generated by the model
    return response.choices[0].message.content.strip()


if __name__ == "__main__":
    while True:
        # Get user input
        user_input = input("You: ")

        # Check if the user wants to exit the conversation
        if user_input.lower() in ["quit", "exit", "bye"]:
            break

        # Call the chatbot function with user input and get the bot's response
        response = chatbot(user_input)

        # Print the bot's response
        print("Bot:", response)
